/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as OrgSecurityRouteImport } from './routes/org/security'
import { Route as OrgMembersRouteImport } from './routes/org/members'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding/company'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocumentsListRouteImport } from './routes/documents/list'
import { Route as DocumentsCreateRouteImport } from './routes/documents/create'
import { Route as AuthUnlockRouteImport } from './routes/auth/unlock'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as SettingsSecurityIndexRouteImport } from './routes/settings/security/index'
import { Route as SettingsSecurityLogsRouteImport } from './routes/settings/security/logs'
import { Route as DocumentsDetailsIdRouteImport } from './routes/documents/details.$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSecurityRoute = OrgSecurityRouteImport.update({
  id: '/org/security',
  path: '/org/security',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgMembersRoute = OrgMembersRouteImport.update({
  id: '/org/members',
  path: '/org/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsListRoute = DocumentsListRouteImport.update({
  id: '/documents/list',
  path: '/documents/list',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsCreateRoute = DocumentsCreateRouteImport.update({
  id: '/documents/create',
  path: '/documents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUnlockRoute = AuthUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SettingsSecurityIndexRoute = SettingsSecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsSecurityRoute,
} as any)
const SettingsSecurityLogsRoute = SettingsSecurityLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsSecurityRoute,
} as any)
const DocumentsDetailsIdRoute = DocumentsDetailsIdRouteImport.update({
  id: '/documents/details/$id',
  path: '/documents/details/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/unlock': typeof AuthUnlockRoute
  '/documents/create': typeof DocumentsCreateRoute
  '/documents/list': typeof DocumentsListRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/org/members': typeof OrgMembersRoute
  '/org/security': typeof OrgSecurityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/documents/details/$id': typeof DocumentsDetailsIdRoute
  '/settings/security/logs': typeof SettingsSecurityLogsRoute
  '/settings/security/': typeof SettingsSecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/unlock': typeof AuthUnlockRoute
  '/documents/create': typeof DocumentsCreateRoute
  '/documents/list': typeof DocumentsListRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/org/members': typeof OrgMembersRoute
  '/org/security': typeof OrgSecurityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/auth': typeof AuthIndexRoute
  '/documents/details/$id': typeof DocumentsDetailsIdRoute
  '/settings/security/logs': typeof SettingsSecurityLogsRoute
  '/settings/security': typeof SettingsSecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/unlock': typeof AuthUnlockRoute
  '/documents/create': typeof DocumentsCreateRoute
  '/documents/list': typeof DocumentsListRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/org/members': typeof OrgMembersRoute
  '/org/security': typeof OrgSecurityRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/documents/details/$id': typeof DocumentsDetailsIdRoute
  '/settings/security/logs': typeof SettingsSecurityLogsRoute
  '/settings/security/': typeof SettingsSecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/unlock'
    | '/documents/create'
    | '/documents/list'
    | '/invite/$token'
    | '/onboarding/company'
    | '/org/members'
    | '/org/security'
    | '/settings/profile'
    | '/settings/security'
    | '/auth/'
    | '/documents/details/$id'
    | '/settings/security/logs'
    | '/settings/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/unlock'
    | '/documents/create'
    | '/documents/list'
    | '/invite/$token'
    | '/onboarding/company'
    | '/org/members'
    | '/org/security'
    | '/settings/profile'
    | '/auth'
    | '/documents/details/$id'
    | '/settings/security/logs'
    | '/settings/security'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/unlock'
    | '/documents/create'
    | '/documents/list'
    | '/invite/$token'
    | '/onboarding/company'
    | '/org/members'
    | '/org/security'
    | '/settings/profile'
    | '/settings/security'
    | '/auth/'
    | '/documents/details/$id'
    | '/settings/security/logs'
    | '/settings/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DocumentsCreateRoute: typeof DocumentsCreateRoute
  DocumentsListRoute: typeof DocumentsListRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OrgMembersRoute: typeof OrgMembersRoute
  OrgSecurityRoute: typeof OrgSecurityRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRouteWithChildren
  DocumentsDetailsIdRoute: typeof DocumentsDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/security': {
      id: '/org/security'
      path: '/org/security'
      fullPath: '/org/security'
      preLoaderRoute: typeof OrgSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/members': {
      id: '/org/members'
      path: '/org/members'
      fullPath: '/org/members'
      preLoaderRoute: typeof OrgMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/list': {
      id: '/documents/list'
      path: '/documents/list'
      fullPath: '/documents/list'
      preLoaderRoute: typeof DocumentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/create': {
      id: '/documents/create'
      path: '/documents/create'
      fullPath: '/documents/create'
      preLoaderRoute: typeof DocumentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/unlock': {
      id: '/auth/unlock'
      path: '/unlock'
      fullPath: '/auth/unlock'
      preLoaderRoute: typeof AuthUnlockRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/settings/security/': {
      id: '/settings/security/'
      path: '/'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof SettingsSecurityIndexRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/settings/security/logs': {
      id: '/settings/security/logs'
      path: '/logs'
      fullPath: '/settings/security/logs'
      preLoaderRoute: typeof SettingsSecurityLogsRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/documents/details/$id': {
      id: '/documents/details/$id'
      path: '/documents/details/$id'
      fullPath: '/documents/details/$id'
      preLoaderRoute: typeof DocumentsDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthUnlockRoute: typeof AuthUnlockRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthUnlockRoute: AuthUnlockRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingsSecurityRouteChildren {
  SettingsSecurityLogsRoute: typeof SettingsSecurityLogsRoute
  SettingsSecurityIndexRoute: typeof SettingsSecurityIndexRoute
}

const SettingsSecurityRouteChildren: SettingsSecurityRouteChildren = {
  SettingsSecurityLogsRoute: SettingsSecurityLogsRoute,
  SettingsSecurityIndexRoute: SettingsSecurityIndexRoute,
}

const SettingsSecurityRouteWithChildren =
  SettingsSecurityRoute._addFileChildren(SettingsSecurityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DocumentsCreateRoute: DocumentsCreateRoute,
  DocumentsListRoute: DocumentsListRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OrgMembersRoute: OrgMembersRoute,
  OrgSecurityRoute: OrgSecurityRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRouteWithChildren,
  DocumentsDetailsIdRoute: DocumentsDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
